# Generated by Django 5.1.3 on 2024-11-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primer_nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
