# Generated by Django 5.1.3 on 2024-11-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_usuario_contraseña_alter_usuario_apellido_materno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
